apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qacpexoo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qacpexoo:62cd65ac6492e0d75e0bddeb8c9ece37252a49f2@sha256:cc38965efc03c2c7678093654dc49af25b1c16ba083e9043ac271d15f875eafe
          name: container-image
